name:                trading-bot
version:             0.1.0.0
github:              "Fxynos/Trading-Bot"
license:             BSD-3-Clause
author:              "Tsoi Vladislav"
maintainer:          "sinerechka0000@gmail.com"
copyright:           "2025 Tsoi Vladislav"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Fxynos/Trading-Bot#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  trading-bot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-conduit >= 2.3.9
    - bytestring >= 0.12.1.0
    - aeson >= 2.2.3.0

tests:
  trading-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
